# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt\ui\AddCar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCarWindow(object):
    def setupUi(self, AddCarWindow):
        AddCarWindow.setObjectName("AddCarWindow")
        AddCarWindow.resize(506, 364)
        self.centralwidget = QtWidgets.QWidget(AddCarWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(272, 231))
        self.frame.setMaximumSize(QtCore.QSize(472, 431))
        self.frame.setStyleSheet("QLineEdit\n"
"{\n"
"background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid steelblue;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"QLineEdit:focus {\n"
" outline:none; }\n"
"\n"
"QLabel{\n"
" text-shadow: -1px -1px #FFF,\n"
"               -2px -2px #FFF,\n"
"               -1px 1px #FFF,\n"
"               -2px 2px #FFF,\n"
"               1px 1px #FFF,\n"
"               2px 2px #FFF,\n"
"               1px -1px #FFF,\n"
"               2px -2px #FFF,\n"
"               -3px -3px 2px #BBB,\n"
"               -3px 3px 2px #BBB,\n"
"               3px 3px 2px #BBB,\n"
"               3px -3px 2px #BBB;\n"
"    color: steelblue;\n"
"    transition: all 1s;\n"
"    font: 15pt \"Comic Sans MS\";\n"
"    font-weight:bold;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_model = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_model.setFont(font)
        self.label_model.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_model.setObjectName("label_model")
        self.gridLayout.addWidget(self.label_model, 2, 0, 1, 1)
        self.edit_model = QtWidgets.QLineEdit(self.frame)
        self.edit_model.setStyleSheet("")
        self.edit_model.setText("")
        self.edit_model.setObjectName("edit_model")
        self.gridLayout.addWidget(self.edit_model, 2, 1, 1, 3)
        self.label_number = QtWidgets.QLabel(self.frame)
        self.label_number.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_number.setObjectName("label_number")
        self.gridLayout.addWidget(self.label_number, 3, 0, 1, 1)
        self.edit_number = QtWidgets.QLineEdit(self.frame)
        self.edit_number.setText("")
        self.edit_number.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_number.setObjectName("edit_number")
        self.gridLayout.addWidget(self.edit_number, 3, 1, 1, 3)
        self.label_type = QtWidgets.QLabel(self.frame)
        self.label_type.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 4, 0, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.frame)
        self.comboBox_type.setMaximumSize(QtCore.QSize(500, 30))
        self.comboBox_type.setStyleSheet("")
        self.comboBox_type.setObjectName("comboBox_type")
        self.gridLayout.addWidget(self.comboBox_type, 4, 1, 1, 2)
        self.label_issue_year = QtWidgets.QLabel(self.frame)
        self.label_issue_year.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_issue_year.setObjectName("label_issue_year")
        self.gridLayout.addWidget(self.label_issue_year, 5, 0, 1, 1)
        self.edit_issue_year = QtWidgets.QLineEdit(self.frame)
        self.edit_issue_year.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_issue_year.setObjectName("edit_issue_year")
        self.gridLayout.addWidget(self.edit_issue_year, 5, 1, 1, 2)
        self.label_color = QtWidgets.QLabel(self.frame)
        self.label_color.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_color.setObjectName("label_color")
        self.gridLayout.addWidget(self.label_color, 6, 0, 1, 1)
        self.edit_color = QtWidgets.QLineEdit(self.frame)
        self.edit_color.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_color.setObjectName("edit_color")
        self.gridLayout.addWidget(self.edit_color, 6, 1, 1, 2)
        self.label_producer = QtWidgets.QLabel(self.frame)
        self.label_producer.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_producer.setObjectName("label_producer")
        self.gridLayout.addWidget(self.label_producer, 0, 0, 1, 2)
        self.btn_add_producer = QtWidgets.QPushButton(self.frame)
        self.btn_add_producer.setMinimumSize(QtCore.QSize(50, 0))
        self.btn_add_producer.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_add_producer.setStyleSheet("QPushButton{\n"
"color: #1db954;\n"
"background:     #121212;\n"
"border-radius: 60px;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}")
        self.btn_add_producer.setObjectName("btn_add_producer")
        self.gridLayout.addWidget(self.btn_add_producer, 0, 3, 1, 1)
        self.comboBox_producer = QtWidgets.QComboBox(self.frame)
        self.comboBox_producer.setMaximumSize(QtCore.QSize(500, 30))
        self.comboBox_producer.setStyleSheet("")
        self.comboBox_producer.setObjectName("comboBox_producer")
        self.gridLayout.addWidget(self.comboBox_producer, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setMinimumSize(QtCore.QSize(181, 41))
        self.btn_add.setStyleSheet("QPushButton{\n"
"color: #1db954;\n"
"background:     #121212;\n"
"border-radius: 60px;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        AddCarWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddCarWindow)
        QtCore.QMetaObject.connectSlotsByName(AddCarWindow)

    def retranslateUi(self, AddCarWindow):
        _translate = QtCore.QCoreApplication.translate
        AddCarWindow.setWindowTitle(_translate("AddCarWindow", "Add car"))
        self.label_model.setText(_translate("AddCarWindow", "Model"))
        self.label_number.setText(_translate("AddCarWindow", "Number"))
        self.label_type.setText(_translate("AddCarWindow", "Select type"))
        self.label_issue_year.setText(_translate("AddCarWindow", "Year of issue"))
        self.label_color.setText(_translate("AddCarWindow", "Color"))
        self.label_producer.setText(_translate("AddCarWindow", "Select producer"))
        self.btn_add_producer.setText(_translate("AddCarWindow", "Add"))
        self.btn_add.setText(_translate("AddCarWindow", "Add"))
