# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt\ui\AddContacts.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPassportWindow(object):
    def setupUi(self, AddPassportWindow):
        AddPassportWindow.setObjectName("AddPassportWindow")
        AddPassportWindow.resize(440, 223)
        AddPassportWindow.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background: steelblue;\n"
"border-radius: 60px;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"QLineEdit\n"
"{\n"
"background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid steelblue;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"QLineEdit:focus {\n"
" outline:none; }\n"
"\n"
"QLabel{\n"
"    color: steelblue;\n"
"    transition: all 1s;\n"
"    font: 14pt \"Comic Sans MS\";\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QDateEdit{\n"
"background: transparent;\n"
"border: none;\n"
"font: 14pt \"Comic Sans MS\";\n"
"color: steelblue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AddPassportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_code = QtWidgets.QLabel(self.frame)
        self.label_code.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_code.setObjectName("label_code")
        self.gridLayout.addWidget(self.label_code, 0, 0, 1, 1)
        self.edit_code = QtWidgets.QLineEdit(self.frame)
        self.edit_code.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_code.setObjectName("edit_code")
        self.gridLayout.addWidget(self.edit_code, 0, 1, 1, 2)
        self.label_phone_number = QtWidgets.QLabel(self.frame)
        self.label_phone_number.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_phone_number.setObjectName("label_phone_number")
        self.gridLayout.addWidget(self.label_phone_number, 1, 0, 1, 2)
        self.edit_phone_number = QtWidgets.QLineEdit(self.frame)
        self.edit_phone_number.setMaximumSize(QtCore.QSize(370, 16777215))
        self.edit_phone_number.setObjectName("edit_phone_number")
        self.gridLayout.addWidget(self.edit_phone_number, 1, 2, 1, 1)
        self.edit_email = QtWidgets.QLineEdit(self.frame)
        self.edit_email.setMaximumSize(QtCore.QSize(370, 16777215))
        self.edit_email.setObjectName("edit_email")
        self.gridLayout.addWidget(self.edit_email, 2, 1, 1, 2)
        self.label_email = QtWidgets.QLabel(self.frame)
        self.label_email.setStyleSheet("QLabel{\n"
"    color:    #535353;\n"
"}")
        self.label_email.setObjectName("label_email")
        self.gridLayout.addWidget(self.label_email, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setMinimumSize(QtCore.QSize(181, 41))
        self.btn_add.setStyleSheet("QPushButton{\n"
"color: #1db954;\n"
"background:     #121212;\n"
"border-radius: 60px;\n"
"font: 12pt \"Comic Sans MS\";\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        AddPassportWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddPassportWindow)
        QtCore.QMetaObject.connectSlotsByName(AddPassportWindow)

    def retranslateUi(self, AddPassportWindow):
        _translate = QtCore.QCoreApplication.translate
        AddPassportWindow.setWindowTitle(_translate("AddPassportWindow", "Add Contacts"))
        self.label_code.setText(_translate("AddPassportWindow", "Code"))
        self.label_phone_number.setText(_translate("AddPassportWindow", "Phone number"))
        self.label_email.setText(_translate("AddPassportWindow", "Email"))
        self.btn_add.setText(_translate("AddPassportWindow", "Add"))
